AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Pipes Google Analytics Raw Data Duplicator

Parameters:
  Name:
    Type: String
    Description: The name of the api
    MinLength: 3
    MaxLength: 30
  Stage:
    Type: String
    Description: The stage of the api
    MinLength: 2
    MaxLength: 20
  AdminEmail:
    Type: String
    Description: An email of the person that should be notified in case missing data 
    Default: cdv-monitoring@apadmi.com
  FallbackEmail:
    Type: String
    Description: An email of the person that should be notified in case of missing data
    Default: cdv-monitoring@apadmi.com
  S3AlarmPeriod:
    Type: String
    Description: Provide a time value in seconds when the alarm should trigger when new data is missing in S3
    Default: 60

Outputs:
  FirehoseBucket:
    Description: Name of the S3 bucket containing GA data
    Value:
      Fn::GetAtt:
        - GoogleAnalyticsCollectorStack
        - Outputs.FirehoseBucket

Resources:

  GoogleAnalyticsCollectorStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./collector-ga.yaml
      Parameters:
        Name:
          Ref: Name
        Stage:
          Ref: Stage
        AdminEmail:
          Ref: AdminEmail
        FallbackEmail:
          Ref: FallbackEmail
        S3AlarmPeriod:
          Ref: S3AlarmPeriod
        EnableGlueTrigger: true
        EnableMonitoring: true
