AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Data Lake ingest pipeline for Footworks
Metadata:
  AWS::ServerlessRepo::Application:
    Name: !Sub 'cdv-data-lake-bf-${Environment}'
    Description: Data Lake ingest pipeline for Footworks
    Author: Apadmi
    Labels: ['cdv']

Parameters:
  Environment:
    Description: Environment being deployed to. This will be used as part of the resource names
    Type: String
  LakeFormationS3AccessRoleArn:
    Description: ARN of the Role in the platform account used by LakeFormation to access product S3 buckets.
    Type: String

Resources:
  $include: ./s3/LandingBucket.yaml
  $include: ./s3/RawBucket.yaml
  $include: ./s3/SensitiveBucket.yaml
  $include: ./s3/CleansedBucket.yaml