RawBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub 'cdv-datalake-raw-fw-${Environment}'

RawBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref RawBucket
    PolicyDocument:
      Statement:
        - Action:
            - s3:ListBucket
          Effect: Allow
          Principal:
            AWS: !Ref LakeFormationS3AccessRoleArn
          Resource: !Sub arn:aws:s3:::${RawBucket}
        - Action:
            - s3:DeleteObject
            - s3:GetObject
            - s3:PutObject
          Effect: Allow
          Principal:
            AWS: !Ref LakeFormationS3AccessRoleArn
          Resource: !Sub arn:aws:s3:::${RawBucket}/*