SensitiveBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub 'cdv-datalake-sensitive-pp-${Environment}'

SensitiveBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref SensitiveBucket
    PolicyDocument:
      Statement:
        - Action:
            - s3:ListBucket
          Effect: Allow
          Principal:
            AWS: !Ref LakeFormationS3AccessRoleArn
          Resource: !Sub arn:aws:s3:::${SensitiveBucket}
        - Action:
            - s3:DeleteObject
            - s3:GetObject
            - s3:PutObject
          Effect: Allow
          Principal:
            AWS: !Ref LakeFormationS3AccessRoleArn
          Resource: !Sub arn:aws:s3:::${SensitiveBucket}/*