# SNS topic which is notified when new pinpoint data arrives in the landing bucket
PinpointLandingDataSnsTopic:
  Type: AWS::SNS::Topic
  Properties:
    TopicName: !Sub 'cdv-datalake-pp-landing-pinpoint-${Environment}'

PinpointLandingDataSnsTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref PinpointLandingDataSnsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sns:Publish'
            Resource: !Ref PinpointLandingDataSnsTopic
            Principal:
              Service: "s3.amazonaws.com"
            Condition:
              ArnLike:
                # Can't use Ref here because it creates a circular dependency between bucket and SNS topic
                AWS:SourceArn: !Sub 'arn:aws:s3:::cdv-datalake-landing-pp-${Environment}' 