KinesisFirehoseRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Service:
          - firehose.amazonaws.com
        Action:
        - sts:AssumeRole

S3DeliveryPolicy:
  Type: AWS::IAM::Policy
  Properties:
    PolicyName: firehose_s3delivery_policy
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action:
            - s3:AbortMultipartUpload
            - s3:GetBucketLocation
            - s3:GetObject
            - s3:ListBucket
            - s3:ListBucketMultipartUploads
            - s3:PutObject
          Resource:
            - !GetAtt LandingBucket.Arn
            - Fn::Join:
              - ""
              - - !GetAtt LandingBucket.Arn
                - "/*"
    Roles:
      - Ref: KinesisFirehoseRole